### ISSUE TITLE
Gives error when afk command is run

### ISSUE THREAD

**Issue by pewpasta** [litecactus/discord_simple_afk_bot#1]
Ignoring exception in command afk:
    Traceback (most recent call last):
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
        ret = await coro(*args, **kwargs)
      File "main.py", line 15, in afk
        if x in current_nick:
    TypeError: argument of type 'NoneType' is not iterable
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 902, in invoke
        await ctx.command.invoke(ctx)
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 864, in invoke
        await injected(*ctx.args, **ctx.kwargs)
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
        raise CommandInvokeError(exc) from exc
    discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: argument of type 'NoneType' is not iterable

**Comment by litecactus** [comment]
I'm using Python3.9.1 are you able to update from 3.8 and see if that fixes?

**Comment by pewpasta** [comment]
I'm getting the same error even on upgrading to Python 3.9
![image](https://user-images.githubusercontent.com/67459484/106483350-7133da00-64d4-11eb-9491-6496c94f9e36.png)
![image](https://user-images.githubusercontent.com/67459484/106483394-7c870580-64d4-11eb-826e-66b3b15280ff.png)

**Comment by litecactus** [comment]
Getting the obvious out the way here, you've installed the discord module for python and entered your specific bot token at the bottom? Assuming that's fine, try adding my bot to your channel for testing (it can't change the channel admins nickname, I think these permissions are correct, but try it and let me know).

https://discord.com/api/oauth2/authorize?client_id=797849377150205973&permissions=201326592&scope=bot

**Comment by pewpasta** [comment]
It isn't working with your bot either. I gave it admin perms too, but it isn't working.
The account using the afk command wasn't a channel admin either.

**Comment by litecactus** [comment]
> It isn't working with your bot either. I gave it admin perms too, but it isn't working.
> The account using the afk command wasn't a channel admin either.

I honestly don't know what to suggest, I have it working on two servers and it is used daily. Have you tried another device?

**Comment by pewpasta** [comment]
Never Mind. Thanks for trying to help tho : )

**Comment by litecactus** [comment]
file updated, check it out again if still relavent?
